{{- range $keyFile := .Values.keyFiles }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: {{ $keyFile.name | required "A resource name is required." }}
  {{- with $keyFile.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $keyFile.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  keyAlgorithm: {{ $keyFile.spec.keyAlgorithm | default "KEY_ALG_RSA_2048" }}
  privateKeyType: {{ $keyFile.spec.privateKeyType | default "TYPE_GOOGLE_CREDENTIALS_FILE" }}
  publicKeyType: {{ $keyFile.spec.publicKeyType | default "TYPE_X509_PEM_FILE" }}
  {{- with $keyFile.spec.serviceAccountRef | required "A serviceAccountRef is required." }}
  serviceAccountRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}