apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: {{ .Values.name | required "A resource name is required." }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "iam-service-account-key.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  keyAlgorithm: {{ .Values.spec.keyAlgorithm | default "KEY_ALG_RSA_2048" }}
  privateKeyType: {{ .Values.spec.privateKeyType | default "TYPE_GOOGLE_CREDENTIALS_FILE" }}
  publicKeyType: {{ .Values.spec.publicKeyType | default "TYPE_X509_PEM_FILE" }}
  {{- with .Values.spec.serviceAccountRef | required "A serviceAccountRef is required." }}
  serviceAccountRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}