{{ range $sa := .Values.serviceAccounts }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ $sa.name | lower | required "Service Account name is required" }}-storagebucket-roles
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "storagebucket.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/{{ $sa.projectId | lower | required "A project ID is required" }}
  bindings:
    - role: {{ $sa.role }}
      condition:
        description: This condition will restrict the policy to a specific bucket.
        expression: resource.name.startsWith("projects/_/buckets/{{ $.Values.name }}")
        title: Restrict Bucket
      members:
        - memberFrom:
            serviceAccountRef:
              name: {{ $sa.name | lower | required "Service Account name is required" }}
---
{{- end }}