# Default values for iam-service-account.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iamserviceaccount

accounts:
# Name of the Config Connector resource.
- name: iamserviceaccount-sample

  # Labels on the Config Connector resource.
  labels: {}

  # Annotations on the Config Connector resource.
  annotations: {}

  spec:
    # A text description of the service account. Must be less than or equal to 256 UTF-8 bytes.
    description: "Description of Service Account"

    # Whether the service account is disabled. Defaults to false.
    #disabled: false

    # The display name for the service account. Can be updated without creating a new resource.
    displayName: Example Service Account

    # Immutable. Optional. The accountId of the resource. Used for creation and acquisition.
    # When unset, the value of `metadata.name` is used as the default.
    #resourceID: ""
