############################################################
#                     Deadletter Topics                    #
############################################################

{{- range $topic := .Values.topics  }}
{{- if $topic.enableDeadletterTopic }}
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: deadletter.{{ $topic.name }}
  {{- if or ($.Values.annotations) ($.Values.argoSyncWave) }}
  annotations:
    {{- with $.Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $.Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ $.Values.argoSyncWave | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "pubsub.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
---
{{- end }}
{{- end }}