############################################################
#                    Deadletter Policies                   #
############################################################

{{- range $topic := .Values.topics  }}
{{- if $topic.enableDeadletterTopic }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: deadletter.{{ $topic.name }}-pub
  {{- if or ($.Values.annotations) ($.Values.argoSyncWave) }}
  annotations:
    {{- with $.Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $.Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ $.Values.argoSyncWave | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "pubsub.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: deadletter.{{ $topic.name }}
  bindings:
    - role: roles/pubsub.publisher
      members:
        - member:  "serviceAccount:service-{{ $.Values.projectNumber }}@gcp-sa-pubsub.iam.gserviceaccount.com"
---
{{- end }}
{{- end }}

{{- range $sub := .Values.subscriptions  }}
{{- if $sub.spec.deadLetterPolicy }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: deadletter.{{ $sub.name }}-sub
  {{- if or ($.Values.annotations) ($.Values.argoSyncWave) }}
  annotations:
    {{- with $.Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $.Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ $.Values.argoSyncWave | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "pubsub.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubSubscription
    name: {{ $sub.name }}
  bindings:
    - role: roles/pubsub.subscriber
      members:
        - member:  "serviceAccount:service-{{ $.Values.projectNumber }}@gcp-sa-pubsub.iam.gserviceaccount.com"
---
{{- end }}
{{- end }}