############################################################
#                PubSub IAM Partial Policy                 #
############################################################

{{- range $topic := .Values.topics  }}
{{- if or $topic.publishers $.Values.globalPublishers }}

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: "pub-role-{{ $topic.name }}"
  {{- if or ($.Values.annotations) ($.Values.argoSyncWave) }}
  annotations:
    {{- with $.Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $.Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ $.Values.argoSyncWave | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "pubsub.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: {{ $topic.name }}
  bindings:
    - role: roles/pubsub.publisher
      members:
        {{- $publishers := concat  ($topic.publishers | default list) $.Values.globalPublishers  }}
        {{- range $sa := $publishers  }}
        - member:  "serviceAccount:{{ $sa }}"
        {{- end }}
---
{{- end }}
{{- end }}


{{- range $sub := .Values.subscriptions }}
{{- if or $sub.subscribers $.Values.globalSubscribers }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: "sub-role-{{ $sub.name }}"
  {{- if or ($.Values.annotations) ($.Values.argoSyncWave) }}
  annotations:
    {{- with $.Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $.Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ $.Values.argoSyncWave | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "pubsub.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubSubscription
    name: {{ $sub.name }}
  bindings:
    - role: roles/pubsub.subscriber
      members:
        {{- $subscribers := concat  ($sub.subscribers | default list) $.Values.globalSubscribers  }}
        {{- range $sa := $subscribers }}
        - member:  "serviceAccount:{{ $sa }}"
        {{- end }}
---
{{- end }}
{{- end }}
