apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: {{ .Values.name | required "A SQL Instance resource name is required." }}
  {{ if or (not .Values.deletionPolicyRemoveResource) (.Values.annotations) -}}
  annotations:
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{ if not .Values.deletionPolicyRemoveResource -}}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end -}}
  {{- end }}
  labels:
    {{- include "sqlinstance.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.spec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}