apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: {{ .Values.name | required "A resource name is required." }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "sqlinstance.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.spec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}