{{- if .Values.keyFile.create }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: {{ .Values.name }}
  {{- with .Values.keyFile.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.keyFile.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  keyAlgorithm: {{ .Values.spec.keyAlgorithm | default "KEY_ALG_RSA_2048" }}
  privateKeyType: {{ .Values.spec.privateKeyType | default "TYPE_GOOGLE_CREDENTIALS_FILE" }}
  publicKeyType: {{ .Values.spec.publicKeyType | default "TYPE_X509_PEM_FILE" }}
  serviceAccountRef:
    name: {{ .Values.name }}
{{- end }}