# Default values for sqlinstance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqlinstance

global:
  # Add labels from a parent chart to all manifests.
  labels: {}

######################################################
#                    SQL Instance                    #
######################################################

name: sqlinstance-sample

# deletionPolicyRemoveResource: true

# Labels on the Config Connector resource.
labels: {}

# Annotations on the Config Connector resource.
annotations: {}

spec:
  databaseVersion: POSTGRES_14
  region: europe-west3
  settings:
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: 8
      enabled: true
      location: eu
      pointInTimeRecoveryEnabled: true
      startTime: 01:00
      transactionLogRetentionDays: 7
    insightsConfig:
      queryInsightsEnabled: true
      recordApplicationTags: true
      recordClientAddress: true
    maintenanceWindow:
      day: 7
      hour: 02
      updateTrack: stable
    availabilityType: REGIONAL
    databaseFlags:
    - name: cloudsql.iam_authentication
      value: "on"
    tier: db-f1-micro


######################################################
#                     Databases                      #
######################################################

# https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqldatabase

# If you leave the "databases" array empty, a default database with the same name as the SQL Instance will be created, with default values.
# If you want another database name or create multiple datebases, add them to the array below with minimum a name. Examples are provided.

databases: []
  # - name: database-01

  # - name: database-02
  #   deletionPolicyRemoveResource: true
  #   annotations:
  #     some-annotation: some-value
  #   spec:
  #     charset: some-other-value
  #     collation: some-other-value


######################################################
#                   Databases Users                  #
######################################################

# https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqluser

# Below array hold the service accounts which should get access.
# The SA will get the "roles/cloudsql.instanceUser" to be able to connect with Cloud SQL Proxy
# and what ever role you define in the "role" property. Role reference https://cloud.google.com/iam/docs/understanding-roles#cloud-sql-roles
serviceAccounts: []
  # - name: my-service-account
  #   projectId: my-google-project-id
  #   role: role/cloudsql.editor
  #   # Below values are optional
  #   deletionPolicyRemoveResource: true
  #   annotations:
  #     some-annotation: some-value
